HEAD /posts HTTP/1.1
Host: jsonplaceholder.typicode.com

###
GET /posts HTTP/1.1
Host: jsonplaceholder.typicode.com

###
POST /posts HTTP/1.1
Host: jsonplaceholder.typicode.com
Content-Type: application/json
Content-Length: 88

{
    "title": "Новая публикация",
    "body": "Текст публикации",
    "userId": 31337
}


###
GET /secret-page HTTP/1.1
Host: myserver.local
Authorization: Basic YWRtaW46MTIzNDU2

###
GET https://jsonplaceholder.typicode.com/comments HTTP/1.1
Content-Type: application/json

###
## Получить комментарии для публикации с идентификатором 1
GET https://jsonplaceholder.typicode.com/comments?postId=1 HTTP/1.1
Content-Type: application/json


###
## Получить список Фильмов
GET http://localhost:4000/films HTTP/1.1
Content-Type: application/json

###
## Создать фильм
POST http://localhost:4000/films HTTP/1.1
Content-Type: application/json

{
  "title": "aviator",
  "description": "aviator aviator aviator ",
  "releaseDate": "2022-01-01",
  "genre": "Drama",
  "publicationDate": "2021-01-01",
  "previewVideoLink": "matrix.mp4",
  "videoLink": "aviator.jpg",
  "starrings": ["aviator1","aviator2"],
  "director": "aviator",
  "runTime": "180",
  "posterImage": "aviator.jpg",
  "backgroundImage": "aviator.jpg",
  "backgroundColor": "#ffffff",
  "userId": "634dd49615778ef82fb5e7b2"
}


###
## Объявление по идентификатору
GET http://localhost:4000/comments/635d71f474077314a4fb4a2f HTTP/1.1


###
## Создание комментария
POST http://localhost:4000/comments/635d71f474077314a4fb4a2f HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ItCf0YDQuNCy0LXRgkDQv9GA0LjQstC10YIucnUiLCJpZCI6IjYzNTU4NmNhODhmNjMxM2Y1MGFlYjEwMCIsImlhdCI6MTY2NzE3NzY2OSwiZXhwIjoxNjY3MzUwNDY5fQ.-mIGdzce09aWTv31sAhcjqRrW1k-fF6OqGXilIDWhxc

{
  "filmId": "635d71f474077314a4fb4a2f",
  "text": "Привет. Фильм норм. Нравицца",
  "date": "2022-01-01",
  "rating": 5
}

//Проверка всех методов фильма
###
## create film1
POST http://localhost:4000/films HTTP/1.1
Content-Type: application/json

{
  "title": "film1",
  "description": "film1 film1 film1 film1",
  "releaseDate": "2022-01-01",
  "genre": "Drama",
  "publicationDate": "2021-01-01",
  "previewVideoLink": "film1.mp4",
  "videoLink": "film1.jpg",
  "starrings": ["film1","film1"],
  "director": "film1",
  "runTime": "180",
  "posterImage": "film1.jpg",
  "backgroundImage": "film1.jpg",
  "backgroundColor": "#ffffff",
  "userId": "634dd49615778ef82fb5e7b2"
}

###
## create film2
POST http://localhost:4000/films HTTP/1.1
Content-Type: application/json

{
  "title": "film2",
  "description": "film2 film2 film2 film2",
  "releaseDate": "2022-01-01",
  "genre": "Romance",
  "publicationDate": "2021-01-01",
  "previewVideoLink": "film2.mp4",
  "videoLink": "film2.jpg",
  "starrings": ["film2","film2"],
  "director": "film2",
  "runTime": "180",
  "posterImage": "film2.jpg",
  "backgroundImage": "film2.jpg",
  "backgroundColor": "#ffffff",
  "userId": "634dd49615778ef82fb5e7b2"
}


###
## updateById
PATCH http://localhost:4000/films/635d638b014acc2b1e1d0d36 HTTP/1.1
Content-Type: application/json

{
  "title": "film1 update",
  "description": "film1 film1 film1 film1",
  "releaseDate": "2022-01-01",
  "genre": "Romance",
  "publicationDate": "2021-01-01",
  "previewVideoLink": "film1.mp4",
  "videoLink": "film1.jpg",
  "starrings": ["film1","film1"],
  "director": "film1",
  "runTime": "180",
  "posterImage": "film1.jpg",
  "backgroundImage": "film1.jpg",
  "backgroundColor": "#ffffff",
  "userId": "634dd49615778ef82fb5e7b2"
}

###
## deleteById
DELETE http://localhost:4000/films/635d638b014acc2b1e1d0d36 HTTP/1.1

###
## index
GET http://localhost:4000/films HTTP/1.1

###
## findByGenre
GET http://localhost:4000/films/genre/Romance HTTP/1.1

###
## findById
GET http://localhost:4000/films/635d6afd8f3454825ab4fbce HTTP/1.1

###
## findPromo
GET http://localhost:4000/films/promo HTTP/1.1


###
## getFavorite
GET http://localhost:4000/films/favorite HTTP/1.1


###
## setFavorite
POST http://localhost:4000/films/favorite/1 HTTP/1.1
Content-Type: application/json

###
## Отправка аватарки пользователю
POST http://localhost:4000/users/634dd49615778ef82fb5e7b2/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< D:/HTMLAcademy/avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
## Создадим пользователя
POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{

  "userName" : "Привет",
  "avatar" : "Привет.jpg",
  "email" : "Привет@привет.ru",
  "password" : "123456"
}

###
## login
POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email" : "Привет@привет.ru",
  "password" : "123"  
}


###

## Проверка токена пользователя
GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ItCf0YDQuNCy0LXRgkDQv9GA0LjQstC10YIucnUiLCJpZCI6IjYzNTU4NmNhODhmNjMxM2Y1MGFlYjEwMCIsImlhdCI6MTY2NzE3NzY2OSwiZXhwIjoxNjY3MzUwNDY5fQ.-mIGdzce09aWTv31sAhcjqRrW1k-fF6OqGXilIDWhxc